#Print sequences greater than 120 aminoacids
seqA="MTNKVNSYGWKALIGSAVGYAMDGFDLLILGFMLSAISADLNLTPAQGGSLVTWTLIGAVFGGILFGALSDKYGRVRVLTWTILLFAVFTGLCAIAQGYWDLLIYRTIAGIGLGGEFGI"
seqB="GMALAAEAWPARHRAKAASYVALGWQVGVLGAALLTPLLLPHIGWRGMFLVGIFPAFVAWFLRSHLHEPEIFTQKQTALSTQSSFTDKLRSFQLLIKDKATSKISLGIVVLTSVQNFGYYG"
seqC="IMIWLPNFLSKQLGFSLTKSGLWTAVTVCGMMAGIWIFGQLADRIGRKPSFLLFQLGAVISIVVYSQLTDPDIMLLAGAFLGMFVNGMLGGYGALMAEAYPTEARATAQNVLFNIGRA"
if len(seqA) > 120:
    print("Sequence A is longer than 120 aa:", seqA)
if len(seqB) > 120:
    print("Sequence B is longer than 120 aa:", seqB)
if len(seqC) > 120:
    print("Sequence C is longer than 120 aa:", seqC)